name: test_plot_png
on: [push, workflow_dispatch]
jobs:
  plot_png:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test
          make clean
          make MODULE=test_png
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: upload png
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: plot_png
          path: |
            test/mandelbrot.png
            test/mandelbrot_py.png
            test/result.xml
